<a href="https://colab.research.google.com/github/sreeparvathitk/python-projects/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#addition and multiplication
import numpy as np
a = np.array([1, 2, 3, 4, 5])
print("Array:", a)
print("Addition:", a + 2)
print("Multiplication:", a * 2)

Array: [1 2 3 4 5]
Addition: [3 4 5 6 7]
Multiplication: [ 2  4  6  8 10]


In [2]:
# mean, median and standard deviation
import numpy as np
a = np.random.randint(1, 100, 10)
print("Array:", a)
print("Mean:", np.mean(a))
print("Median:", np.median(a))
print("Standard Deviation:", np.std(a))

Array: [16 83 66 93 69 94 90 99 52 33]
Mean: 69.5
Median: 76.0
Standard Deviation: 26.717971479885968


In [3]:
#Reshape
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(2, 3)
print("Original array:", a)
print("Reshaped array:")
print(b)

Original array: [1 2 3 4 5 6]
Reshaped array:
[[1 2 3]
 [4 5 6]]


In [4]:
# sum and product of array elements
import numpy as np
numbers = [1, 2, 3, 4, 5]
a = np.array(numbers)
print("Array:", a)
print("Sum:", np.sum(a))
print("Product:", np.prod(a))

Array: [1 2 3 4 5]
Sum: 15
Product: 120


In [5]:
# 0 to 9 and reshape into a 3×3 matrix
import numpy as np
a = np.arange(9)
matrix = a.reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
# Mean,median and standard deviation of a dataset
import numpy as np
data = np.array([10, 20, 30, 40, 50])
print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Standard Deviation:", np.std(data))

Mean: 30.0
Median: 30.0
Standard Deviation: 14.142135623730951


In [8]:
# Sort an array in ascending order
import numpy as np
def sort_array(numbers):
    a = np.array(numbers)
    return np.sort(a)
numbers = [5,2,8,1,3]
print("Sorted array:", sort_array(numbers))

Sorted array: [1 2 3 5 8]


In [9]:
# Sum of each row and column
import numpy as np
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print("Array:")
print(a)
print("Row sums:", np.sum(a, axis=1))
print("Column sums:", np.sum(a, axis=0))

Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Row sums: [ 6 15 24]
Column sums: [12 15 18]


In [10]:
#Random array — maximum and minimum
import numpy as np
a = np.random.randint(1, 100, 10)
print("Array:", a)
print("Maximum:", np.max(a))
print("Minimum:", np.min(a))

Array: [87  6 17 99 44 20 68 74 74 15]
Maximum: 99
Minimum: 6


In [11]:
# Square every element of an array
import numpy as np
def square_array(a):
 return a ** 2
a = np.array([1, 2, 3, 4, 5])
print("Original array:", a)
print("Squared array:", square_array(a))

Original array: [1 2 3 4 5]
Squared array: [ 1  4  9 16 25]


In [12]:
# Dot product
import numpy as np
a = np.array([1, 2, 3, 4])
result = np.dot(a, a)
print("Dot product:", result)

Dot product: 30


In [13]:
# Inverse
import numpy as np
matrix = np.array([
    [1, 2],
    [3, 4]
])
inverse = np.linalg.inv(matrix)
print("Matrix:")
print(matrix)
print("Inverse:")
print(inverse)

Matrix:
[[1 2]
 [3 4]]
Inverse:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [14]:
# Transpose
import numpy as np
def transpose_array(a):
    return a.T
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print("Original array:")
print(a)
print("Transpose:")
print(transpose_array(a))

Original array:
[[1 2 3]
 [4 5 6]]
Transpose:
[[1 4]
 [2 5]
 [3 6]]
